version: "3.6"
services:
  git-server:
    image: opensafely/git-server-proxy
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
      - ./read-only-keys:/git-server/read-only-keys
      - ./read-write-keys:/git-server/read-write-keys
      - ./master-key:/git-server/master-key
